### ISSUE TITLE
Add function to replace wrapper around point

### ISSUE THREAD

**Issue by rranelli** [rejeep/wrap-region.el#27]
Hi,

I've been using this package for quite some time now and I wrote a function to replace current wrapper at point for another one.

You can check the function [here](https://github.com/rranelli/emacs-dotfiles/blob/master/lisp/init-edit-defuns.el#L51)

Is it okay for me to issue a PR with the feature?

Thanks!

**Comment by rejeep** [comment]
Personally I don't think wrap-region is complex enough to provide these features. In your snippet you have to specify what wrapper you want to replace. With packages such as [Smartparens](https://github.com/Fuco1/smartparens) you can ask for wrappers around point for example.

So, I want to keep wrap-region quite simple. Smartparens is more suitable for things such as this. I don't even use wrap-region anymore because Smartparens is so awesome and more powerful!

But thanks anyways!

**Comment by rranelli** [comment]
Nice. I did not know smartparens. Will definitely take a look at it.

Thanks.
